### PR TITLE
Improve readability of Content component

### PR DESCRIPTION
**Pull request by dkumiszhan**
This should address #66.

### CODE REVIEW

**Comment by dkumiszhan** [comment]
@glaslos could you describe what you meant in https://github.com/honeynet/ochi/issues/66#issuecomment-1627686906?

**Comment by glaslos** [comment]
I use a lot of `<br />` instead of CSS styling ;)

**Comment by dkumiszhan** [comment]
> I use a lot of `<br />` instead of CSS styling ;)

Let me handle those in a separate PR. For this one I am just adding custom row styles.

**Review by glaslos — APPROVED** [review]
LGTM

**Pull request merged**
